### ISSUE TITLE
赞一个

### ISSUE THREAD

**Issue by dtboy1995** [boiledwater/count-down#1]
正好用到了，写的很好，赞一个。扫了一眼github就这个比较简洁明了，建议作者可以可以多加些例子代码，继续完善下库，感谢。
- 给项目整个logo
- 把演示图弄成gif

**Comment by boiledwater** [comment]
收到

**Comment by dtboy1995** [comment]
@boiledwater 小程序可以加载外部npm包吗，如果可以的话，您可以发布到npm上，我开发用的是wepy，对原生小程序的资源调用不是太懂，如果可以加载的话用户下载这个库也方便了

**Comment by boiledwater** [comment]
不太了解小程序是否可以加载外部npm包。我查下资料先；
